// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heoteyiobtlykkwjwrrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhlb3RleWlvYnRseWtrd2p3cnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTI5MTAsImV4cCI6MjA3Mzg4ODkxMH0.WkJ43wyl58kXJCwgaIVDfBcttIcelwffY9ywuADm8DE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});